export const ROLE_BN: Record<string, string> = {
  Owner: "প্রতিষ্ঠাতা ও সিইও",
  Chairman: "চেয়ারম্যান",
  MD: "ম্যানেজিং ডিরেক্টর",
  Admin: "অ্যাডমিন",
  Manager: "জেনারেল ম্যানেজার",
  HR: "এইচআর",
  Accounts: "হিসাবরক্ষণ",
  Sales: "মার্কেটিং",
  "Project Manager": "প্রজেক্ট ম্যানেজার",
  Engineer: "ইঞ্জিনিয়ার",
  Staff: "স্টাফ",
  "Site Staff": "সাইট স্টাফ",
};

export const NAV_BN = {
  dashboard: "ড্যাশবোর্ড",
  attendance: "হাজিরা",
  myDay: "আমার দিন",
  dailyWorks: "দৈনিক কাজ",
  tasks: "টাস্ক",
  siteReports: "সাইট রিপোর্ট",
  leads: "লিড ও ফলো-আপ",
  clients: "ক্লায়েন্ট",
  quotations: "কোটেশন",
  projects: "প্রজেক্ট",
  sites: "সাইট",
  materials: "মালামাল",
  inventory: "ইনভেন্টরি",
  purchaseOrders: "ক্রয় অর্ডার",
  suppliers: "সাপ্লায়ার",
  labour: "শ্রমিক ও ঠিকাদার",
  accounts: "হিসাব",
  invoices: "ইনভয়েস (AR)",
  income: "আয়",
  expenses: "খরচ",
  payments: "পেমেন্ট",
  employees: "কর্মচারী",
  payroll: "পে-রোল",
  leave: "ছুটি",
  performance: "পারফরম্যান্স",
  reports: "রিপোর্ট",
  documents: "ডকুমেন্ট",
  notifications: "নোটিফিকেশন",
  users: "ব্যবহারকারী",
  settings: "সেটিংস",
  logout: "লগ আউট",
  login: "লগ ইন",
  announcements: "ঘোষণা",
  profile: "প্রোফাইল",
};

export const MSG = {
  saved: "সংরক্ষণ হয়েছে — ডাটাবেস আপডেট হয়েছে",
  failed: "কাজটি সম্পন্ন হয়নি",
  network: "নেটওয়ার্ক সমস্যা",
  loading: "INSAF ERP লোড হচ্ছে...",
  sessionCheck: "সেশন ও অনুমতি যাচাই করা হচ্ছে",
  accessDenied: "প্রবেশাধিকার নেই",
  mustChangePassword: "প্রথম লগইন — পাসওয়ার্ড পরিবর্তন বাধ্যতামূলক",
};
